services:
  # The bot itself, record into raw, unusable files
  pandora:
    # build:
    #   context: ../..
    container_name: pandora
    image: pandora-local:v1.5
    restart: on-failure:5
    depends_on:
      - redis
      - placement
    environment:
      # Discord bot token
      - PANDORA_TOKEN=${PANDORA_TOKEN}
      # Prefix for text-based command
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      # Dapr component for state storage
      - STORE_NAME=${STORE_NAME}
      - OBJECT_STORE_NAME=${OBJECT_STORE_NAME}
      # - PUBSUB_NAME=${PUBSUB_NAME}

      # Dapr callback port
      - DAPR_SERVER_PORT=${DAPR_SERVER_PORT}
      # Sidecar port
      - DAPR_HTTP_PORT=${DAPR_HTTP_PORT}
      - DAPR_HOST=${DAPR_HOST}
      - DOMAIN=${DOMAIN}
      - NODE_ENV=production
    volumes:
      - /tmp/pandora:/app/rec
      - /mnt/bucket:/app/bucket
    networks:
      - discord_recordings
  # Dapr sidecar, defining runtime implementations
  pandora-dapr:
    image: "daprio/daprd:edge"
    container_name: pandora-dapr
    command: [ "./daprd", "-app-id", "pandora", "-app-port", "${DAPR_SERVER_PORT}", "-dapr-http-port", "${DAPR_HTTP_PORT}", "--max-body-size", "1200Ki", "-placement-host-address", "placement:50006", "-resources-path", "./components", "--dapr-graceful-shutdown-seconds", "20" ]
    # In docker-compose, you have to provide components by sharing a volume
    restart: always
    # this is the dapr/components directory
    ports:
      - "${DAPR_HTTP_PORT}:${DAPR_HTTP_PORT}"
    volumes:
      - "./components/:/components"
    networks:
      - discord_recordings
  meetpod:
    image: meetpod-local:v1.1
    container_name: meetpod
    restart: on-failure:5
    depends_on:
      - pandora
    volumes:
      - /mnt/bucket:/mnt/bucket
    ports:
      - "3000:3000" 
    # this is the dapr/components directory
    networks:
      - discord_recordings

  placement:
    image: "daprio/dapr"
    restart: always

    command: [ "./placement", "-port", "50006" ]
    ports:
      - "50006:50006"
    networks:
      - discord_recordings
  # Converts the raw files into audio files
  pandora-cooking-server:
    # image: sotrx/pandora-cooking-server:2.4.4
    image: pandora-cook-local:v2

    container_name: pandora-cooking-server
    ports:
      - "3004:3004"
    restart: always
    volumes:
      - /mnt/bucket:/app/rec
    networks:
      - discord_recordings

  # State store
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - discord_recordings
    # Default docker network doesn't always provide name resolution
    # so we create a new one
networks:
  discord_recordings:
